framework:
    messenger:
        transports:
            # Uncomment the following line to enable a transport named "amqp"
             amqp: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            '*': amqp

       ############
        default_bus: messenger.bus.commands

       ##############
        buses:
          messenger.bus.commands: ~
          messenger.bus.events: ~